inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - spec/**/*.rb
    - 'config/initializers/*'

Metrics/AbcSize:
  Max: 24
  Exclude:
    - 'db/migrate/20250331082829_create_doorkeeper_tables.rb'

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - 'config/environments/*'

Metrics/MethodLength:
  Max: 26
  Exclude:
    - 'db/migrate/20250331082829_create_doorkeeper_tables.rb'

Rails/BulkChangeTable:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments
  Exclude:
    - 'spec/features/answer/create_spec.rb'
    - 'spec/features/answer/edit_spec.rb'
    - 'spec/features/question/create_spec.rb'
    - 'spec/features/question/reward/add_reward_spec.rb'
    - 'spec/controllers/rewards_controller_spec.rb'
    - 'spec/features/reward/add_reward_to_question_spec.rb'
    - 'spec/features/reward/index_reward_spec.rb'

Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/20250331082829_create_doorkeeper_tables.rb'

Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/20240803184522_add_best_to_answers.rb'
    - 'db/migrate/20250331085735_add_admin_to_users.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Exclude:
    - 'spec/controllers/rewards_controller_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 7

RSpec/LetSetup:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'db/migrate/20250331082829_create_doorkeeper_tables.rb'
